% maze topology

path(start, junction)
path(junction, start)
path(junction, path_a)
path(path_a, junction)
path(junction, path_b)
path(path_b, junction)
path(junction, path_c)
path(path_c, junction)
path(trigger_a, trigger_b)
path(trigger_b, trigger_a)
path(path_a, trigger_a)
path(trigger_a, path_a)
closed_gate(path_a, trigger_a)
closed_gate(trigger_a, path_a)
trigger(path_a, trigger_a, junction)
trigger(trigger_a, path_a, junction)
path(path_b, path_b1)
path(path_b1, path_b)
path(path_b1, path_b2)
path(path_b2, path_b1)
closed_gate(path_b1, path_b2)
closed_gate(path_b2, path_b1)
trigger(path_b1, path_b2, trigger_b)
trigger(path_b2, path_b1, trigger_b)
path(path_b2, path_b3)
path(path_b3, path_b2)
path(path_b3, end)
path(end, path_b3)
closed_gate(path_b3, end)
closed_gate(end, path_b3)
trigger(path_b3, end, trigger_c)
trigger(end, path_b3, trigger_c)
path(path_c, trigger_c)
path(trigger_c, path_c)


% bandits

at(bandit_0, start)
